-- Criar tabela de clientes

CREATE TABLE CLIENTE(
				ID UNIQUEIDENTIFIER NOT NULL,
				NOME NVARCHAR(100) NOT NULL,
				CPF NVARCHAR(11) NOT NULL,
				DATANASCIMENTO DATE NOT NULL,
				PRIMARY KEY(ID))

-- INSERIR UM NOVO CLIENTE
INSERT INTO CLIENTE (ID,NOME, CPF,DATANASCIMENTO) VALUES (NEWID(),'JACK BIG LOVE','12345678900','04-01-23 10:34:09 AM')

-- MOSTRAR TODOS OS CAMPOS DE CLIENTES

SELECT * FROM CLIENTE;

delete from CLIENTE where NOME = 'JACK BIG LOVE'