CREATE TABLE FUNCIONARIO(
				ID UNIQUEIDENTIFIER NOT NULL,
				NOME NVARCHAR(100) NOT NULL,
				CPF NVARCHAR(11) NOT NULL,
				DATAADMISSAO DATE NOT NULL,
				TIPOCONTRATACAO INTEGER NOT NULL,
				PRIMARY KEY(ID))

CREATE TABLE ENDERECO(
				ID UNIQUEIDENTIFIER NOT NULL,
				LOGRADOURO NVARCHAR(100) NOT NULL,
				COMPLEMENTO NVARCHAR(100) NOT NULL,
				BAIRRO NVARCHAR(100) NOT NULL,
				CIDADE NVARCHAR(100) NOT NULL,
				ESTADO NVARCHAR(25) NOT NULL,
				CEP NVARCHAR(10) NOT NULL,
				IDFUNCIONARIO UNIQUEIDENTIFIER NOT NULL UNIQUE,
				PRIMARY KEY(ID),
				FOREIGN KEY(IDFUNCIONARIO) REFERENCES FUNCIONARIO(ID))

            INSERT INTO FUNCIONARIO (ID, NOME, CPF, DATAADMISSAO, TIPOCONTRATACAO)
                VALUES (NEWID(), 'Jonas Monteiro', '13410453741', '04-01-23 10:34:09 AM', '1')

			INSERT INTO FUNCIONARIO (ID, LOGRADOURO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, IDFUNCIONARIO)
                VALUES (NEWID(), 'Rua X', 'numero 1500', 'Barra da Tijuca', 'Rio de Janeiro', 'RJ', '22775033', 'B8789234-62ED-4288-A1A5-8CC89BF0C479')

				select * from FUNCIONARIO;
				