CREATE PROCEDURE SP_INSERIR_FUNCIONARIO
	@P_IDFUNCIONARIO	UNIQUEIDENTIFIER,
	@P_NOME				NVARCHAR(150),
	@P_CPF				NVARCHAR(14),
	@P_DATAADMISSAO		DATE,
	@P_TIPOCONTRATACAO	INTEGER,
	@P_IDENDERECO		UNIQUEIDENTIFIER,
	@P_LOGRADOURO		NVARCHAR(150),
	@P_COMPLEMENTO		NVARCHAR(100),
	@P_BAIRRO			NVARCHAR(100),
	@P_CIDADE			NVARCHAR(100),
	@P_ESTADO			NVARCHAR(25),
	@P_CEP				NVARCHAR(10)
AS
BEGIN
	
	BEGIN TRANSACTION

	INSERT INTO FUNCIONARIO(
		ID, 
		NOME, 
		CPF, 
		DATAADMISSAO, 
		TIPOCONTRATACAO)
	VALUES(
		@P_IDFUNCIONARIO, 
		@P_NOME, 
		@P_CPF, 
		@P_DATAADMISSAO, 
		@P_TIPOCONTRATACAO)

	INSERT INTO ENDERECO(
		ID,
		LOGRADOURO,
		COMPLEMENTO,
		BAIRRO,
		CIDADE,
		ESTADO,
		CEP,
		IDFUNCIONARIO)
	VALUES(
		@P_IDENDERECO,
		@P_LOGRADOURO,
		@P_COMPLEMENTO,
		@P_BAIRRO,
		@P_CIDADE,
		@P_ESTADO,
		@P_CEP,
		@P_IDFUNCIONARIO
	)

	COMMIT
END
GO

